Android o
feedhenry-templates/helloworld-android-gradle pull request #26
Opened 2017-07-31 18:26 UTC by secondsun

2017-08-03 11:44 UTC, damienomurchu requested changes
code changes fine, but bug in template that will require https://github.com/secondsun/helloworld-android-gradle/pull/1 to be merged before this pr can be

2017-08-09 08:08 UTC, damienomurchu approved these changes

2017-08-10 14:07 UTC, danielpassos approved these changes

2017-08-10 14:07 UTC, danielpassos commented
Landed at Android-O branch https://github.com/feedhenry-templates/helloworld-android-gradle/commit/7c266704a051a2517f90768318b19f79fd42c640

2017-08-10 14:07 UTC, closed without merging